version: '3'

services:
  ngrok:
    container_name: ngrok
    image: ${NGROK_IMAGE}
    command:
      - "start"
      - "--all"
      - "--config"
      - "${NGROK_ADDITIONAL_CONFIG_FILES}"
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - ${NGROK_PORT}:4040
    volumes:
      - ${HOST_NGROK_CONFIG_DIR}:${CONTAINER_NGROK_CONFIG_DIR}